name: Rust

on:
  push:
    branches: [ rust ]
  pull_request:
    branches: [ rust ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check compilation
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
